name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        activate-environment: ivychat
        environment-file: environment.yml
        python-version: 3.8
    - name: Install dependencies
      run: |
        mamba env update --file requirements.txt
    - name: Run pytest
      run: |
        pytest
